---
- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present
    update_cache: true

- name: Hold kubectl at current version
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold