---
- hosts: control_plane
  become: true
  tasks:
    - name: kubeadm init
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory

    - name: Copy admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: true

    - name: Get join command
      command: kubeadm token create --print-join-command
      register: join_command
      changed_when: false

    - name: Save join command as fact
      set_fact:
        kubeadm_join_cmd: "{{ join_command.stdout }}"

    - name: Install Tigera Operator
      command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.31.5/manifests/tigera-operator.yaml

    - name: Install Calico Custom Resources
      command: kubectl create -f kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.31.5/manifests/custom-resources.yaml